[package]
name = "main"
version = "0.1.0"
authors = ["Hungkhoaitay <e0550385@u.nus.edu>", "giterator <e055220@u.nus.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = 1

[features]
default = ["by_radius"]
by_radius = []
by_knn = []

[lib]
name = "iswr"
path = "src/lib.rs"

[dependencies]
ply-rs = "0.1.3"
kiss3d = { git = "https://github.com/nus-mmsys/kiss3d", version = "0.31.0" }
nalgebra = "0.26.2"
kiddo =  {git = "https://github.com/giterator/kiddo"}  #"0.1.4"
typenum = "1.13.0"
rand = "0.8.3"
lab = "0.10.0"
clap = "2.33.3"
error-chain = "0.12.4"
image        = "0.23"

[[bin]]
name = "ply_to_ply"

[[bin]]
name = "ply_view"

[[bin]]
name = "ply_to_png"

[[bin]]
name = "ply_interpolate"

[[bin]]
name = "ply_fat"

[[bin]]
name = "test"