[package]
name = "in-summer-we-render"
version = "0.1.0"
authors = ["Hungkhoaitay <e0550385@u.nus.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ply-rs = "0.1.3"
kiss3d = "0.31.0"
nalgebra = "0.26.2"
kd-tree = "0.3.0"
typenum = "1.13.0"
rand = "0.8.3"
lab = "0.10.0"