[package]
name = "in-summer-we-render"
version = "0.1.0"
authors = ["Hungkhoaitay <e0550385@u.nus.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
